### ISSUE TITLE
In App Updates feature not working in Android 14 

### ISSUE THREAD

**Issue by chganesh** [import-yuv/react-native-inapp-update#2]
In App Updates feature shows Popup or Screen asking your users to update app depending upon your urgency requirements.

**Comment by chganesh** [comment]
@import-yuv i Tried Based on this example 
https://codingzest.com/how-to-implement-in-app-update-in-android-application/  not worked for me. but your provided example working fine in below android 14 version of Android.

Please help me one this. 
Thanks in Advance

**Comment by import-yuv** [comment]
Hey @chganesh, Please look into [this](https://developer.android.com/reference/com/google/android/play/core/release-notes-in_app_updates).

Also make changes in your app's build.gradle ([reference](https://developer.android.com/guide/playcore#groovy))
